### ISSUE TITLE
Suggest: Roundcube instead of Squirremail

### ISSUE THREAD

**Issue by PatrickHuetter** [jerob/docker-ispconfig#3]
It would be fine to have roundcube as web mail client instead of Squirremail.

**Comment by TomKremer** [comment]
+1

**Comment by storcksoftware** [comment]
+1 Not an issue, but a kind request. And also, thank you for all your work!

**Comment by eigood** [comment]
For a while there, roundcube was not available in debian(it used to be, but then got removed).  It's been re-added in testing, and jessie-backports, but it's not in jessie itself.  Since this Dockerfile is based on jessie, it was never an option during the initial build.

Fyi, I am not the original creator.

**Comment by jerob** [comment]
The dockerfile now use debian stretch.

Thank you for the suggest, roundcube is available https://localhost:8080/webmail/
