### ISSUE TITLE
Creating image fails currently

### ISSUE THREAD

**Issue by sprijk** [jerob/docker-ispconfig#4]
Can you verify if creating an image still works (using ISPconfig 3.1)? Thanks!

**Comment by eigood** [comment]
I am not the author, but did you actually have a problem yourself when you tried it, or are  you just fishing?  If you had a real problem, please provide those details.  It's possible others might also have the problem, and doing google searches will then show this up.

**Comment by eigood** [comment]
I've had no issues with the build other than because of my own tweaking, but I'm still using 3.0.

**Comment by eigood** [comment]
Ok, I see what is going on.  *Creation* of the image does not fail; however, running the built image *does* fail.  This is due to the Dockerfile fetching ISPConfig-3-stable, which has changed from 3.0.5 to 3.1, and the list of requirements is different enough that the output of the Dockerfile no longer functions.

This is going to be a bit difficult to fix; the 3-stable download now points to 3.1, which is too big of a version change that I'd like to introduce right now.  If I attempt to download previous versions(3.0.5, 3.0.5.4), via sourceforge, the tarballs do *not* have autoinstall support(it's not mentioned inside install.php).  It looks like the ispconfig release process lost the changes.

The stable-3.0.5 branch has the autoinstall patches, but not the 3.0.5 nor 3.0.5.4 branches.

The fix here seems to be an upgrade to 3.1.2, which does have the required autoinstall support.

**Comment by jerob** [comment]
The dockerfile is now compatible with Ispconfig 3.1, thank you
